REGIONAL_INDICATOR_N = "\U0001F1F3"
REGIONAL_INDICATOR_O = "\U0001F1F4"

CROSS_MARK = "\U0000274C"
WHITE_CHECK_MARK = "\U00002705"

KEYCAP_ONE = "1️⃣"
KEYCAP_TWO = "2️⃣"
KEYCAP_THREE = "3️⃣"
KEYCAP_FOUR = "4️⃣"
KEYCAP_FIVE = "5️⃣"
KEYCAP_SIX = "6️⃣"
KEYCAP_SEVEN = "7️⃣"
KEYCAP_EIGHT = "8️⃣"
KEYCAP_NINE = "9️⃣"
KEYCAP_TEN = "🔟"
KEYCAP_NUMBERS = [
    KEYCAP_ONE,
    KEYCAP_TWO,
    KEYCAP_THREE,
    KEYCAP_FOUR,
    KEYCAP_FIVE,
    KEYCAP_SIX,
    KEYCAP_SEVEN,
    KEYCAP_EIGHT,
    KEYCAP_NINE,
    KEYCAP_TEN
]